const n5Data = [
  {
    Kanji: "浴びる",
    Vocabulary: "abiru あびる",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to bathe, to shower",
  },
  {
    Kanji: "危ない",
    Vocabulary: "abunai あぶない",
    Type: "Adjective, い-adjective",
    Meaning: "dangerous",
  },
  {
    Kanji: "あっち",
    Vocabulary: "acchi",
    Type: "Pronoun",
    Meaning: "over there",
  },
  {
    Kanji: "あちら",
    Vocabulary: "achira",
    Type: "Pronoun",
    Meaning: "there",
  },
  {
    Kanji: "上げる",
    Vocabulary: "ageru あげる",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to raise; to elevate",
  },
  {
    Kanji: "赤",
    Vocabulary: "aka あか",
    Type: "Noun",
    Meaning: "red; crimson; scarlet​",
  },
  {
    Kanji: "赤い",
    Vocabulary: "akai あかい",
    Type: "Adjective, い-adjective",
    Meaning: "red; crimson; scarlet​",
  },
  {
    Kanji: "明るい",
    Vocabulary: "akarui あかるい",
    Type: "Adjective, い-adjective",
    Meaning: "bright; light",
  },
  {
    Kanji: "開ける",
    Vocabulary: "akeru あける",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to open (a door, etc.); to unwrap (e.g. parcel, package); to unlock",
  },
  {
    Kanji: "秋",
    Vocabulary: "aki あき",
    Type: "Noun",
    Meaning: "autumn; fall",
  },
  {
    Kanji: "開く",
    Vocabulary: "aku あく",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to open (e.g. doors, business, etc)",
  },
  {
    Kanji: "甘い",
    Vocabulary: "amai あまい",
    Type: "Adjective, い-adjective",
    Meaning: "sweet; sweet-tasting; sugary; naive; indulgent",
  },
  {
    Kanji: "飴",
    Vocabulary: "ame あめ",
    Type: "Noun",
    Meaning: "candy",
  },
  {
    Kanji: "雨",
    Vocabulary: "ame あめ",
    Type: "Noun",
    Meaning: "rain",
  },
  {
    Kanji: "あなた",
    Vocabulary: "anata",
    Type: "Pronoun",
    Meaning: "you",
  },
  {
    Kanji: "姉",
    Vocabulary: "ane あね",
    Type: "Noun",
    Meaning: "older sister; elder sister​",
  },
  {
    Kanji: "兄",
    Vocabulary: "ani あに",
    Type: "Noun",
    Meaning: "elder brother; older brother​",
  },
  {
    Kanji: "あの",
    Vocabulary: "ano",
    Type: "Pre-noun adjectival",
    Meaning: "that",
  },
  {
    Kanji: "青",
    Vocabulary: "ao あお",
    Type: "Noun",
    Meaning: "blue; azure",
  },
  {
    Kanji: "青い",
    Vocabulary: "aoi あおい",
    Type: "Adjective, い-adjective",
    Meaning: "blue; azure",
  },
  {
    Kanji: "アパート",
    Vocabulary: "apaato",
    Type: "Noun, Katakana",
    Meaning: "apartment",
  },
  {
    Kanji: "洗う",
    Vocabulary: "arau あらう",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to wash",
  },
  {
    Kanji: "あれ",
    Vocabulary: "are",
    Type: "Pronoun",
    Meaning: "that",
  },
  {
    Kanji: "ある",
    Vocabulary: "aru",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to be, to have",
  },
  {
    Kanji: "歩く",
    Vocabulary: "aruku あるく",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to walk",
  },
  {
    Kanji: "朝",
    Vocabulary: "asa あさ",
    Type: "Noun",
    Meaning: "morning",
  },
  {
    Kanji: "朝ご飯",
    Vocabulary: "asagohan あさごはん",
    Type: "Noun",
    Meaning: "breakfast",
  },
  {
    Kanji: "明後日",
    Vocabulary: "asatte あさって",
    Type: "Noun",
    Meaning: "day after tomorrow",
  },
  {
    Kanji: "足",
    Vocabulary: "ashi あし",
    Type: "Noun",
    Meaning: "foot; leg; paw; arm",
  },
  {
    Kanji: "明日",
    Vocabulary: "ashita あした",
    Type: "Noun, Temporal noun",
    Meaning: "tomorrow",
  },
  {
    Kanji: "遊ぶ",
    Vocabulary: "asobu あそぶ",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to play; to enjoy oneself",
  },
  {
    Kanji: "あそこ",
    Vocabulary: "asoko",
    Type: "Pronoun",
    Meaning: "over there",
  },
  {
    Kanji: "頭",
    Vocabulary: "atama あたま",
    Type: "Noun",
    Meaning: "head",
  },
  {
    Kanji: "新しい",
    Vocabulary: "atarashii あたらしい",
    Type: "Adjective, い-adjective",
    Meaning: "new; novel; fresh; recent; latest",
  },
  {
    Kanji: "暖かい",
    Vocabulary: "atatakai あたたかい",
    Type: "Adjective, い-adjective",
    Meaning: "warm",
  },
  {
    Kanji: "後",
    Vocabulary: "ato あと",
    Type: "Noun",
    Meaning: "behind; after; remainder; left; also",
  },
  {
    Kanji: "厚い",
    Vocabulary: "atsui あつい",
    Type: "Adjective, い-adjective",
    Meaning: "thick",
  },
  {
    Kanji: "暑い",
    Vocabulary: "atsui あつい",
    Type: "Adjective, い-adjective",
    Meaning: "hot; sultry",
  },
  {
    Kanji: "熱い",
    Vocabulary: "atsui あつい",
    Type: "Adjective, い-adjective",
    Meaning: "hot",
  },
  {
    Kanji: "会う",
    Vocabulary: "au あう",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to meet; to encounter; to see",
  },
  {
    Kanji: "晩ご飯",
    Vocabulary: "bangohan ばんごはん",
    Type: "Noun",
    Meaning: "dinner; evening meal",
  },
  {
    Kanji: "番号",
    Vocabulary: "bangou ばんごう",
    Type: "Noun",
    Meaning: "number",
  },
  {
    Kanji: "バス",
    Vocabulary: "basu",
    Type: "Noun, Katakana",
    Meaning: "bus",
  },
  {
    Kanji: "バター",
    Vocabulary: "bataa",
    Type: "Noun, Katakana",
    Meaning: "butter​",
  },
  {
    Kanji: "ベッド",
    Vocabulary: "beddo",
    Type: "Noun, Katakana",
    Meaning: "bed",
  },
  {
    Kanji: "勉強",
    Vocabulary: "benkyou べんきょう",
    Type: "Noun, Suru verb",
    Meaning: "to study",
  },
  {
    Kanji: "便利",
    Vocabulary: "benri べんり",
    Type: "な-adjective",
    Meaning: "convenient; handy; useful",
  },
  {
    Kanji: "ボールペン",
    Vocabulary: "boorupen",
    Type: "Noun, Katakana",
    Meaning: "ball-point pen",
  },
  {
    Kanji: "ボタン",
    Vocabulary: "botan",
    Type: "Noun, Katakana",
    Meaning: "button",
  },
  {
    Kanji: "帽子",
    Vocabulary: "boushi ぼうし",
    Type: "Noun",
    Meaning: "hat; cap",
  },
  {
    Kanji: "文章",
    Vocabulary: "bunshou ぶんしょう",
    Type: "Noun",
    Meaning: "sentence",
  },
  {
    Kanji: "豚肉",
    Vocabulary: "butaniku ぶたにく",
    Type: "Noun",
    Meaning: "pork",
  },
  {
    Kanji: "病院",
    Vocabulary: "byouin びょういん",
    Type: "Noun",
    Meaning: "hospital",
  },
  {
    Kanji: "病気",
    Vocabulary: "byouki びょうき",
    Type: "Noun",
    Meaning: "illness; disease; sickness",
  },
  {
    Kanji: "茶色",
    Vocabulary: "chairo ちゃいろ",
    Type: "Noun",
    Meaning: "brown",
  },
  {
    Kanji: "茶碗",
    Vocabulary: "chawan ちゃわん",
    Type: "Noun",
    Meaning: "rice bowl; tea cup; teacup",
  },
  {
    Kanji: "父",
    Vocabulary: "chichi ちち",
    Type: "Noun",
    Meaning: "father",
  },
  {
    Kanji: "違う",
    Vocabulary: "chigau ちがう",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to differ",
  },
  {
    Kanji: "小さい",
    Vocabulary: "chiisai ちいさい",
    Type: "Adjective, い-adjective",
    Meaning: "small; little; tiny",
  },
  {
    Kanji: "小さな",
    Vocabulary: "chiisana ちいさな",
    Type: "Pre-noun adjectival",
    Meaning: "small; little; tiny​",
  },
  {
    Kanji: "近い",
    Vocabulary: "chikai ちかい",
    Type: "い-adjective",
    Meaning: "near; close",
  },
  {
    Kanji: "地下鉄",
    Vocabulary: "chikatetsu ちかてつ",
    Type: "Noun",
    Meaning: "subway; underground train",
  },
  {
    Kanji: "地図",
    Vocabulary: "chizu ちず",
    Type: "Noun",
    Meaning: "map",
  },
  {
    Kanji: "ちょっと",
    Vocabulary: "chotto",
    Type: "Adverb",
    Meaning: "a little",
  },
  {
    Kanji: "丁度",
    Vocabulary: "choudo ちょうど",
    Type: "Adverb",
    Meaning: "exactly",
  },
  {
    Kanji: "台所",
    Vocabulary: "daidokoro だいどころ",
    Type: "Noun",
    Meaning: "kitchen",
  },
  {
    Kanji: "大学",
    Vocabulary: "daigaku だいがく",
    Type: "Noun",
    Meaning: "university; college",
  },
  {
    Kanji: "大丈夫",
    Vocabulary: "daijoubu だいじょうぶ",
    Type: "Adjective, な-adjective, Adverb",
    Meaning: "OK; okay; alright; problem free",
  },
  {
    Kanji: "大好き",
    Vocabulary: "daisuki だいすき",
    Type: "Adjective, な-adjective",
    Meaning: "love; like; like very much",
  },
  {
    Kanji: "だんだん",
    Vocabulary: "dandan",
    Type: "Adverb",
    Meaning: "gradually",
  },
  {
    Kanji: "誰",
    Vocabulary: "dare だれ",
    Type: "Pronoun",
    Meaning: "who",
  },
  {
    Kanji: "誰か",
    Vocabulary: "dareka だれか",
    Type: "Pronoun",
    Meaning: "someone; somebody",
  },
  {
    Kanji: "出す",
    Vocabulary: "dasu だす",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to take out; to get out; to put out; to reveal",
  },
  {
    Kanji: "出口",
    Vocabulary: "deguchi でぐち",
    Type: "Noun",
    Meaning: "exit; gateway; way out",
  },
  {
    Kanji: "出かける",
    Vocabulary: "dekakeru でかける",
    Type: "Verb, Ichidan verb, Intransitive verb",
    Meaning: "to go out; to leave; to depart",
  },
  {
    Kanji: "電気",
    Vocabulary: "denki でんき",
    Type: "Noun",
    Meaning: "electricity",
  },
  {
    Kanji: "電車",
    Vocabulary: "densha でんしゃ",
    Type: "Noun",
    Meaning: "train; electric train",
  },
  {
    Kanji: "電話",
    Vocabulary: "denwa でんわ",
    Type: "Noun, Verb, Suru verb",
    Meaning: "telephone (call / device)l; phone call",
  },
  {
    Kanji: "デパート",
    Vocabulary: "depaato",
    Type: "Noun, Katakana",
    Meaning: "department store",
  },
  {
    Kanji: "出る",
    Vocabulary: "deru でる",
    Type: "Verb, Ichidan verb, Intransitive verb",
    Meaning: "to leave; to exit; to appear; to go out",
  },
  {
    Kanji: "ドア",
    Vocabulary: "doa",
    Type: "Noun, Katakana",
    Meaning: "door",
  },
  {
    Kanji: "どっち",
    Vocabulary: "docchi",
    Type: "Pronoun",
    Meaning: "which; which one",
  },
  {
    Kanji: "どちら",
    Vocabulary: "dochira",
    Type: "Pronoun",
    Meaning: "which of two",
  },
  {
    Kanji: "どこ",
    Vocabulary: "doko",
    Type: "Pronoun",
    Meaning: "where; what place​",
  },
  {
    Kanji: "どなた",
    Vocabulary: "donata",
    Type: "Noun",
    Meaning: "who",
  },
  {
    Kanji: "どの",
    Vocabulary: "dono",
    Type: "Pre-noun adjectival",
    Meaning: "which",
  },
  {
    Kanji: "どれ",
    Vocabulary: "dore",
    Type: "Pronoun",
    Meaning: "which (of three or more)​",
  },
  {
    Kanji: "どう",
    Vocabulary: "dou",
    Type: "Adverb",
    Meaning: "how; in what way; how about​",
  },
  {
    Kanji: "動物",
    Vocabulary: "doubutsu どうぶつ",
    Type: "Noun",
    Meaning: "animal",
  },
  {
    Kanji: "どうも",
    Vocabulary: "doumo",
    Type: "Adverb",
    Meaning: "thank you; thanks",
  },
  {
    Kanji: "どうぞ",
    Vocabulary: "douzo",
    Type: "Adverb",
    Meaning: "please",
  },
  {
    Kanji: "土曜日",
    Vocabulary: "doyoubi どようび",
    Type: "Noun",
    Meaning: "Saturday",
  },
  {
    Kanji: "絵",
    Vocabulary: "e え",
    Type: "Noun",
    Meaning: "picture",
  },
  {
    Kanji: "ええ",
    Vocabulary: "ee",
    Type: "Noun",
    Meaning: "yes; that is correct; right",
  },
  {
    Kanji: "映画",
    Vocabulary: "eiga えいが",
    Type: "Noun",
    Meaning: "movie; film",
  },
  {
    Kanji: "映画館",
    Vocabulary: "eigakan えいがかん",
    Type: "Noun",
    Meaning: "movie theater; cinema",
  },
  {
    Kanji: "英語",
    Vocabulary: "eigo えいご",
    Type: "Noun",
    Meaning: "English language",
  },
  {
    Kanji: "駅",
    Vocabulary: "eki えき",
    Type: "Noun",
    Meaning: "station",
  },
  {
    Kanji: "鉛筆",
    Vocabulary: "enpitsu えんぴつ",
    Type: "Noun",
    Meaning: "pencil",
  },
  {
    Kanji: "エレベーター",
    Vocabulary: "erebeetaa",
    Type: "Noun, Katakana",
    Meaning: "elevator",
  },
  {
    Kanji: "フィルム",
    Vocabulary: "firumu",
    Type: "Noun, Katakana",
    Meaning: "film",
  },
  {
    Kanji: "フォーク",
    Vocabulary: "fooku",
    Type: "Noun, Katakana",
    Meaning: "fork",
  },
  {
    Kanji: "吹く",
    Vocabulary: "fuku ふく",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to blow (of the wind)",
  },
  {
    Kanji: "服",
    Vocabulary: "fuku ふく",
    Type: "Noun",
    Meaning: "clothes",
  },
  {
    Kanji: "降る",
    Vocabulary: "furu ふる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to fall",
  },
  {
    Kanji: "古い",
    Vocabulary: "furui ふるい",
    Type: "い-adjective",
    Meaning: "old (not used for people)",
  },
  {
    Kanji: "二人",
    Vocabulary: "futari ふたり",
    Type: "Noun",
    Meaning: "two people; pair; couple",
  },
  {
    Kanji: "二つ",
    Vocabulary: "futatsu ふたつ",
    Type: "Noun, Numeric",
    Meaning: "two; 2",
  },
  {
    Kanji: "太い",
    Vocabulary: "futoi ふとい",
    Type: "Adjective, い-adjective",
    Meaning: "fat; thick",
  },
  {
    Kanji: "二日",
    Vocabulary: "futsuka ふつか",
    Type: "Noun",
    Meaning: "the second day of the month / 2 days",
  },
  {
    Kanji: "封筒",
    Vocabulary: "fuutou ふうとう",
    Type: "Noun",
    Meaning: "envelope",
  },
  {
    Kanji: "冬",
    Vocabulary: "fuyu ふゆ",
    Type: "Noun",
    Meaning: "winter",
  },
  {
    Kanji: "外国",
    Vocabulary: "gaikoku がいこく",
    Type: "Noun",
    Meaning: "foreign country",
  },
  {
    Kanji: "外国人",
    Vocabulary: "gaikokujin がいこくじん",
    Type: "Noun",
    Meaning: "foreigner; foreign citizen; foreign national; alien; non-Japanese",
  },
  {
    Kanji: "学校",
    Vocabulary: "gakkou がっこう",
    Type: "Noun",
    Meaning: "school",
  },
  {
    Kanji: "学生",
    Vocabulary: "gakusei がくせい",
    Type: "Noun",
    Meaning: "student",
  },
  {
    Kanji: "玄関",
    Vocabulary: "genkan げんかん",
    Type: "Noun",
    Meaning: "entrance",
  },
  {
    Kanji: "元気",
    Vocabulary: "genki げんき",
    Type: "Noun, Adjective, な-adjective",
    Meaning: "lively; full of spirit; energetic; healthy",
  },
  {
    Kanji: "月曜日",
    Vocabulary: "getsuyoubi げつようび",
    Type: "Noun",
    Meaning: "Monday",
  },
  {
    Kanji: "銀行",
    Vocabulary: "ginkou ぎんこう",
    Type: "Noun",
    Meaning: "bank",
  },
  {
    Kanji: "ギター",
    Vocabulary: "gitaa",
    Type: "Noun, Katakana",
    Meaning: "guitar",
  },
  {
    Kanji: "五",
    Vocabulary: "go ご",
    Type: "Noun, Numeric",
    Meaning: "five; 5",
  },
  {
    Kanji: "午後",
    Vocabulary: "gogo ごご",
    Type: "Noun",
    Meaning: "afternoon; p.m.",
  },
  {
    Kanji: "ご飯",
    Vocabulary: "gohan ごはん",
    Type: "Noun",
    Meaning: "cooked rice, meal",
  },
  {
    Kanji: "午前",
    Vocabulary: "gozen ごぜん",
    Type: "Noun",
    Meaning: "morning; a.m.",
  },
  {
    Kanji: "グラム",
    Vocabulary: "guramu",
    Type: "Noun, Katakana",
    Meaning: "gram",
  },
  {
    Kanji: "牛肉",
    Vocabulary: "gyuuniku ぎ? うにく",
    Type: "Noun",
    Meaning: "beef",
  },
  {
    Kanji: "牛乳",
    Vocabulary: "gyuunyuu ぎ? うに? う",
    Type: "Noun",
    Meaning: "(cow's) milk",
  },
  {
    Kanji: "歯",
    Vocabulary: "ha は",
    Type: "Noun",
    Meaning: "tooth",
  },
  {
    Kanji: "八",
    Vocabulary: "hachi はち",
    Type: "Noun, Numeric",
    Meaning: "eight: 8",
  },
  {
    Kanji: "葉書",
    Vocabulary: "hagaki はがき",
    Type: "Noun",
    Meaning: "postcard",
  },
  {
    Kanji: "母",
    Vocabulary: "haha はは",
    Type: "Noun",
    Meaning: "mother",
  },
  {
    Kanji: "はい",
    Vocabulary: "hai",
    Type: "Noun",
    Meaning: "yes; that is correct​",
  },
  {
    Kanji: "入る",
    Vocabulary: "hairu はいる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to enter; to go into",
  },
  {
    Kanji: "灰皿",
    Vocabulary: "haizara はいざら",
    Type: "Noun",
    Meaning: "ashtray",
  },
  {
    Kanji: "始まる",
    Vocabulary: "hajimaru はじまる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to begin",
  },
  {
    Kanji: "初めて",
    Vocabulary: "hajimete はじめて",
    Type: "Adverb",
    Meaning: "for the first time",
  },
  {
    Kanji: "箱",
    Vocabulary: "hako はこ",
    Type: "Noun",
    Meaning: "box; crate",
  },
  {
    Kanji: "履く",
    Vocabulary: "haku はく",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to wear, to put on trousers",
  },
  {
    Kanji: "半",
    Vocabulary: "han はん",
    Type: "Noun",
    Meaning: "half; semi-; half-past",
  },
  {
    Kanji: "花",
    Vocabulary: "hana はな",
    Type: "Noun",
    Meaning: "flower",
  },
  {
    Kanji: "鼻",
    Vocabulary: "hana はな",
    Type: "Noun",
    Meaning: "nose",
  },
  {
    Kanji: "話",
    Vocabulary: "hanashi はなし",
    Type: "Noun",
    Meaning: "talk; speech; chat; conversation​",
  },
  {
    Kanji: "話す",
    Vocabulary: "hanasu はなす",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to speak; to talk; to converse",
  },
  {
    Kanji: "半分",
    Vocabulary: "hanbun はんぶん",
    Type: "Noun",
    Meaning: "half",
  },
  {
    Kanji: "ハンカチ",
    Vocabulary: "hankachi",
    Type: "Noun, Katakana",
    Meaning: "handkerchief​",
  },
  {
    Kanji: "晴れ",
    Vocabulary: "hare はれ",
    Type: "Noun",
    Meaning: "clear weather",
  },
  {
    Kanji: "晴れる",
    Vocabulary: "hareru はれる",
    Type: "Verb, Ichidan verb, Intransitive verb",
    Meaning: "to be sunny",
  },
  {
    Kanji: "貼る",
    Vocabulary: "haru はる",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to stick; to paste",
  },
  {
    Kanji: "春",
    Vocabulary: "haru はる",
    Type: "Noun",
    Meaning: "spring; springtime",
  },
  {
    Kanji: "箸",
    Vocabulary: "hashi はし",
    Type: "Noun",
    Meaning: "chopsticks",
  },
  {
    Kanji: "橋",
    Vocabulary: "hashi はし",
    Type: "Noun",
    Meaning: "bridge",
  },
  {
    Kanji: "走る",
    Vocabulary: "hashiru はしる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to run",
  },
  {
    Kanji: "二十歳",
    Vocabulary: "hatachi はたち",
    Type: "Noun",
    Meaning: "20 years old; twenty years old",
  },
  {
    Kanji: "働く",
    Vocabulary: "hataraku はたらく",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to work",
  },
  {
    Kanji: "二十日",
    Vocabulary: "hatsuka はつか",
    Type: "Noun",
    Meaning: "twentieth day of the month / 20 days",
  },
  {
    Kanji: "早い",
    Vocabulary: "hayai はやい",
    Type: "Adjective, い-adjective",
    Meaning: "fast; early",
  },
  {
    Kanji: "速い",
    Vocabulary: "hayai はやい",
    Type: "Adjective, い-adjective",
    Meaning: "fast; quick; hasty; brisk",
  },
  {
    Kanji: "辺",
    Vocabulary: "hen へん",
    Type: "Noun",
    Meaning: "area",
  },
  {
    Kanji: "下手",
    Vocabulary: "heta へた",
    Type: "Noun, Adjective, な-adjective",
    Meaning: "unskillful; poor; awkward​",
  },
  {
    Kanji: "部屋",
    Vocabulary: "heya へや",
    Type: "Noun",
    Meaning: "room",
  },
  {
    Kanji: "左",
    Vocabulary: "hidari ひだり",
    Type: "Noun",
    Meaning: "left; left hand side",
  },
  {
    Kanji: "東",
    Vocabulary: "higashi ひがし",
    Type: "Noun",
    Meaning: "east",
  },
  {
    Kanji: "飛行機",
    Vocabulary: "hikouki ひこうき",
    Type: "Noun",
    Meaning: "airplane; aircraft",
  },
  {
    Kanji: "引く",
    Vocabulary: "hiku ひく",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to pull",
  },
  {
    Kanji: "弾く",
    Vocabulary: "hiku ひく",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to play",
  },
  {
    Kanji: "低い",
    Vocabulary: "hikui ひくい",
    Type: "い-adjective",
    Meaning: "short,low",
  },
  {
    Kanji: "暇",
    Vocabulary: "hima ひま",
    Type: "Noun, な-adjective",
    Meaning: "free time",
  },
  {
    Kanji: "広い",
    Vocabulary: "hiroi ひろい",
    Type: "い-adjective",
    Meaning: "spacious; vast; wide",
  },
  {
    Kanji: "昼",
    Vocabulary: "hiru ひる",
    Type: "Noun",
    Meaning: "noon; midday; daytime; lunch",
  },
  {
    Kanji: "昼ご飯",
    Vocabulary: "hirugohan ひるごはん",
    Type: "Noun",
    Meaning: "lunch",
  },
  {
    Kanji: "人",
    Vocabulary: "hito ひと",
    Type: "Noun",
    Meaning: "person; human",
  },
  {
    Kanji: "一人",
    Vocabulary: "hitori ひとり",
    Type: "Noun, Adverb",
    Meaning: "one person​; alone; single",
  },
  {
    Kanji: "一つ",
    Vocabulary: "hitotsu ひとつ",
    Type: "Noun, Numeric",
    Meaning: "one thing; only",
  },
  {
    Kanji: "ほか",
    Vocabulary: "hoka",
    Type: "Noun",
    Meaning: "other (place, thing, person); the rest",
  },
  {
    Kanji: "本",
    Vocabulary: "hon ほん",
    Type: "Noun",
    Meaning: "book; volume; script",
  },
  {
    Kanji: "本棚",
    Vocabulary: "hondana ほんだな",
    Type: "Noun",
    Meaning: "bookshelf; bookcase",
  },
  {
    Kanji: "本当",
    Vocabulary: "hontou ほんとう",
    Type: "Noun, Adjective, な-adjective",
    Meaning: "truth; reality; actuality; fact",
  },
  {
    Kanji: "欲しい",
    Vocabulary: "hoshii ほしい",
    Type: "Adjective, い-adjective",
    Meaning: "want",
  },
  {
    Kanji: "細い",
    Vocabulary: "hosoi ほそい",
    Type: "Adjective, い-adjective",
    Meaning: "thin; slender",
  },
  {
    Kanji: "ホテル",
    Vocabulary: "hoteru",
    Type: "Noun, Katakana",
    Meaning: "hotel",
  },
  {
    Kanji: "百",
    Vocabulary: "hyaku ひゃく",
    Type: "Noun, Numeric",
    Meaning: "100; hundred",
  },
  {
    Kanji: "一",
    Vocabulary: "ichi いち",
    Type: "Noun, Prefix, Suffix, Numeric",
    Meaning: "one; best; first; foremost; start",
  },
  {
    Kanji: "一番",
    Vocabulary: "ichiban いちばん",
    Type: "Noun, Adverb",
    Meaning: "number one; first; 1st, first place​; best; most​",
  },
  {
    Kanji: "一日",
    Vocabulary: "ichinichi いちにち",
    Type: "Noun, Adverbial Noun",
    Meaning: "one day, all day",
  },
  {
    Kanji: "家",
    Vocabulary: "ie いえ",
    Type: "Noun",
    Meaning: "house, residence, family",
  },
  {
    Kanji: "いかが",
    Vocabulary: "ikaga",
    Type: "Adverb",
    Meaning: "how; in what way; how about​",
  },
  {
    Kanji: "池",
    Vocabulary: "ike いけ",
    Type: "Noun",
    Meaning: "pond",
  },
  {
    Kanji: "行く",
    Vocabulary: "iku いく",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to go; to move",
  },
  {
    Kanji: "いくら",
    Vocabulary: "ikura",
    Type: "Noun, Adverb",
    Meaning: "how much?; how many?​",
  },
  {
    Kanji: "いくつ",
    Vocabulary: "ikutsu",
    Type: "Adverb",
    Meaning: "how many?,how old?",
  },
  {
    Kanji: "今",
    Vocabulary: "ima いま",
    Type: "Noun, Adverbial Noun",
    Meaning: "now; the present time; soon",
  },
  {
    Kanji: "意味",
    Vocabulary: "imi いみ",
    Type: "Noun",
    Meaning: "meaning; significance; sense",
  },
  {
    Kanji: "妹",
    Vocabulary: "imouto いもうと",
    Type: "Noun",
    Meaning: "younger sister",
  },
  {
    Kanji: "犬",
    Vocabulary: "inu いぬ",
    Type: "Noun",
    Meaning: "dog",
  },
  {
    Kanji: "入れる",
    Vocabulary: "ireru いれる",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to put in; to let in; to take in; to bring in; to insert; to install",
  },
  {
    Kanji: "入口",
    Vocabulary: "iriguchi いりぐち",
    Type: "Noun",
    Meaning: "entrance; entry; gate",
  },
  {
    Kanji: "色",
    Vocabulary: "iro いろ",
    Type: "Noun",
    Meaning: "colour; color",
  },
  {
    Kanji: "色々",
    Vocabulary: "iroiro いろいろ",
    Type: "Noun, Adjective, な-adjective, Adverb",
    Meaning: "various",
  },
  {
    Kanji: "居る",
    Vocabulary: "iru いる",
    Type: "Verb, Ichidan verb, Intransitive verb",
    Meaning: "to be, to have",
  },
  {
    Kanji: "要る",
    Vocabulary: "iru いる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to be needed",
  },
  {
    Kanji: "医者",
    Vocabulary: "isha いしゃ",
    Type: "Noun",
    Meaning: "(medical) doctor; physician",
  },
  {
    Kanji: "忙しい",
    Vocabulary: "isogashii いそがしい",
    Type: "Adjective, い-adjective",
    Meaning: "busy",
  },
  {
    Kanji: "一緒",
    Vocabulary: "issho いっしょ",
    Type: "Noun",
    Meaning: "together; at the same time; same; identical",
  },
  {
    Kanji: "椅子",
    Vocabulary: "isu いす",
    Type: "Noun",
    Meaning: "chair",
  },
  {
    Kanji: "痛い",
    Vocabulary: "itai いたい",
    Type: "Adjective, い-adjective",
    Meaning: "painful; sore​",
  },
  {
    Kanji: "いつ",
    Vocabulary: "itsu",
    Type: "Pronoun",
    Meaning: "when",
  },
  {
    Kanji: "五日",
    Vocabulary: "itsuka いつか",
    Type: "Noun",
    Meaning: "the fifth day of the month / 5 days",
  },
  {
    Kanji: "五つ",
    Vocabulary: "itsutsu いつつ",
    Type: "Noun, Numeric",
    Meaning: "five; 5",
  },
  {
    Kanji: "言う",
    Vocabulary: "iu いう",
    Type: "Verb, Godan verb",
    Meaning: "to say; to call",
  },
  {
    Kanji: "嫌",
    Vocabulary: "iya いや",
    Type: "Noun, Adjective, な-adjective",
    Meaning: "unpleasant",
  },
  {
    Kanji: "じゃあ",
    Vocabulary: "jaa",
    Type: "Conjunction",
    Meaning: "then; well; so; well then",
  },
  {
    Kanji: "字引",
    Vocabulary: "jibiki じびき",
    Type: "Noun",
    Meaning: "dictionary",
  },
  {
    Kanji: "自分",
    Vocabulary: "jibun じぶん",
    Type: "Pronoun",
    Meaning: "myself; yourself; oneself; himself; herself; i; me",
  },
  {
    Kanji: "自動車",
    Vocabulary: "jidousha じどうしゃ",
    Type: "Noun",
    Meaning: "automobile; motorcar; motor vehicle; car",
  },
  {
    Kanji: "時間",
    Vocabulary: "jikan じかん",
    Type: "Noun",
    Meaning: "time; hour(s)",
  },
  {
    Kanji: "辞書",
    Vocabulary: "jisho じしょ",
    Type: "Noun",
    Meaning: "dictionary",
  },
  {
    Kanji: "自転車",
    Vocabulary: "jitensha じてんしゃ",
    Type: "Noun",
    Meaning: "bicycle",
  },
  {
    Kanji: "丈夫",
    Vocabulary: "joubu じょうぶ",
    Type: "Adjective, な-adjective",
    Meaning: "strong, durable",
  },
  {
    Kanji: "上手",
    Vocabulary: "jouzu じょうず",
    Type: "Noun, Adjective, な-adjective",
    Meaning: "skillful; skilled; proficient; good (at)",
  },
  {
    Kanji: "授業",
    Vocabulary: "jugyou じ? ぎょう",
    Type: "Noun, Suru verb",
    Meaning: "lesson; class work",
  },
  {
    Kanji: "十",
    Vocabulary: "juu じ? う",
    Type: "Noun, Numeric",
    Meaning: "ten; 10",
  },
  {
    Kanji: "かばん",
    Vocabulary: "kaban",
    Type: "Noun",
    Meaning: "bag; basket​",
  },
  {
    Kanji: "花瓶",
    Vocabulary: "kabin かびん",
    Type: "Noun",
    Meaning: "a vase",
  },
  {
    Kanji: "角",
    Vocabulary: "kado かど",
    Type: "Noun",
    Meaning: "a corner; angle​",
  },
  {
    Kanji: "帰る",
    Vocabulary: "kaeru かえる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to go back​",
  },
  {
    Kanji: "返す",
    Vocabulary: "kaesu かえす",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to return something",
  },
  {
    Kanji: "鍵",
    Vocabulary: "kagi かぎ",
    Type: "Noun",
    Meaning: "key",
  },
  {
    Kanji: "階段",
    Vocabulary: "kaidan かいだん",
    Type: "Noun",
    Meaning: "stairs; stairway; staircase",
  },
  {
    Kanji: "買い物",
    Vocabulary: "kaimono かいもの",
    Type: "Noun",
    Meaning: "shopping; purchased goods",
  },
  {
    Kanji: "会社",
    Vocabulary: "kaisha かいしゃ",
    Type: "Noun",
    Meaning: "company; corporation",
  },
  {
    Kanji: "掛かる",
    Vocabulary: "kakaru かかる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to take (a resource, e.g. time or money)",
  },
  {
    Kanji: "掛ける",
    Vocabulary: "kakeru かける",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to hang up; to make (a call)​;",
  },
  {
    Kanji: "書く",
    Vocabulary: "kaku かく",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to write; to compose; to pen; to draw",
  },
  {
    Kanji: "カメラ",
    Vocabulary: "kamera",
    Type: "Noun, Katakana",
    Meaning: "camera",
  },
  {
    Kanji: "紙",
    Vocabulary: "kami かみ",
    Type: "Noun",
    Meaning: "paper",
  },
  {
    Kanji: "漢字",
    Vocabulary: "kanjiかんじ",
    Type: "Noun",
    Meaning: "kanji",
  },
  {
    Kanji: "カップ",
    Vocabulary: "kappu",
    Type: "Noun, Katakana",
    Meaning: "cup",
  },
  {
    Kanji: "体",
    Vocabulary: "karada からだ",
    Type: "Noun",
    Meaning: "body",
  },
  {
    Kanji: "辛い",
    Vocabulary: "karai からい",
    Type: "い-adjective",
    Meaning: "spicy",
  },
  {
    Kanji: "カレー",
    Vocabulary: "karee",
    Type: "Noun, Katakana",
    Meaning: "curry",
  },
  {
    Kanji: "カレンダー",
    Vocabulary: "karendaa",
    Type: "Noun, Katakana",
    Meaning: "calendar",
  },
  {
    Kanji: "借りる",
    Vocabulary: "kariru かりる",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to borrow",
  },
  {
    Kanji: "軽い",
    Vocabulary: "karui かるい",
    Type: "Adjective, い-adjective",
    Meaning: "light",
  },
  {
    Kanji: "傘",
    Vocabulary: "kasa かさ",
    Type: "Noun",
    Meaning: "umbrella",
  },
  {
    Kanji: "貸す",
    Vocabulary: "kasu かす",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to lend; to loan",
  },
  {
    Kanji: "方",
    Vocabulary: "kata かた",
    Type: "Noun",
    Meaning: "way of doing something",
  },
  {
    Kanji: "家庭",
    Vocabulary: "katei かてい",
    Type: "Noun",
    Meaning: "household",
  },
  {
    Kanji: "買う",
    Vocabulary: "kau かう",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to buy; to purchase",
  },
  {
    Kanji: "川",
    Vocabulary: "kawa かわ",
    Type: "Noun, Suffix",
    Meaning: "river; stream​",
  },
  {
    Kanji: "可愛い",
    Vocabulary: "kawaii かわいい",
    Type: "Adjective, い-adjective",
    Meaning: "cute",
  },
  {
    Kanji: "火曜日",
    Vocabulary: "kayoubi かようび",
    Type: "Noun",
    Meaning: "Tuesday",
  },
  {
    Kanji: "風邪",
    Vocabulary: "kaze かぜ",
    Type: "Noun",
    Meaning: "a cold",
  },
  {
    Kanji: "風",
    Vocabulary: "kaze かぜ",
    Type: "Noun",
    Meaning: "wind",
  },
  {
    Kanji: "家族",
    Vocabulary: "kazoku かぞく",
    Type: "Noun",
    Meaning: "family; members of a family",
  },
  {
    Kanji: "警官",
    Vocabulary: "keikan けいかん",
    Type: "Noun",
    Meaning: "policeman; police officer",
  },
  {
    Kanji: "結婚",
    Vocabulary: "kekkon けっこん",
    Type: "Noun, Suru verb",
    Meaning: "marriage",
  },
  {
    Kanji: "結構",
    Vocabulary: "kekkou けっこう",
    Type: "Noun, Adverbial Noun, Adjective, な-adjective, Adverb",
    Meaning: "splendid, enough",
  },
  {
    Kanji: "今朝",
    Vocabulary: "kesa けさ",
    Type: "Noun, Temporal noun",
    Meaning: "this morning",
  },
  {
    Kanji: "消す",
    Vocabulary: "kesu けす",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to erase, to turn off power",
  },
  {
    Kanji: "木",
    Vocabulary: "ki き",
    Type: "Noun",
    Meaning: "tree; shrub; bush; wood; timber",
  },
  {
    Kanji: "消える",
    Vocabulary: "kieru きえる",
    Type: "Verb, Ichidan verb, Intransitive verb",
    Meaning: "to disappear",
  },
  {
    Kanji: "黄色い",
    Vocabulary: "kiiroi きいろい",
    Type: "Adjective, い-adjective",
    Meaning: "yellow",
  },
  {
    Kanji: "聞く",
    Vocabulary: "kiku きく",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to hear; to listen (to music); to ask; to learn of",
  },
  {
    Kanji: "昨日",
    Vocabulary: "kinou きのう",
    Type: "Noun",
    Meaning: "yesterday",
  },
  {
    Kanji: "金曜日",
    Vocabulary: "kinyoubi きんようび",
    Type: "Noun",
    Meaning: "Friday",
  },
  {
    Kanji: "切符",
    Vocabulary: "kippu きっぷ",
    Type: "Noun",
    Meaning: "ticket",
  },
  {
    Kanji: "嫌い",
    Vocabulary: "kirai きらい",
    Type: "Noun, Adjective, な-adjective",
    Meaning: "hate",
  },
  {
    Kanji: "綺麗",
    Vocabulary: "kirei きれい",
    Type: "Adjective, な-adjective",
    Meaning: "pretty; lovely; beautiful",
  },
  {
    Kanji: "キログラム",
    Vocabulary: "kiro-guramu",
    Type: "Noun, Katakana",
    Meaning: "kilogram",
  },
  {
    Kanji: "キロメートル",
    Vocabulary: "kiro-meetoru",
    Type: "Noun, Katakana",
    Meaning: "kilometer",
  },
  {
    Kanji: "切る",
    Vocabulary: "kiru きる",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to cut",
  },
  {
    Kanji: "着る",
    Vocabulary: "kiru きる",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to wear",
  },
  {
    Kanji: "喫茶店",
    Vocabulary: "kissaten きっさてん",
    Type: "Noun",
    Meaning: "coffee shop; tearoom; cafe",
  },
  {
    Kanji: "北",
    Vocabulary: "kita きた",
    Type: "Noun",
    Meaning: "north",
  },
  {
    Kanji: "汚い",
    Vocabulary: "kitanai きたない",
    Type: "Adjective, い-adjective",
    Meaning: "dirty",
  },
  {
    Kanji: "切手",
    Vocabulary: "kitte きって",
    Type: "Noun",
    Meaning: "stamp (postage)",
  },
  {
    Kanji: "こっち",
    Vocabulary: "kocchi",
    Type: "Noun",
    Meaning: "this person or way",
  },
  {
    Kanji: "こちら",
    Vocabulary: "kochira",
    Type: "Noun",
    Meaning: "this way; this direction​",
  },
  {
    Kanji: "子供",
    Vocabulary: "kodomo こども",
    Type: "Noun",
    Meaning: "child",
  },
  {
    Kanji: "声",
    Vocabulary: "koe こえ",
    Type: "Noun",
    Meaning: "voice",
  },
  {
    Kanji: "ここ",
    Vocabulary: "koko",
    Type: "Pronoun",
    Meaning: "here; this place",
  },
  {
    Kanji: "九日",
    Vocabulary: "kokonoka ここのか",
    Type: "Noun",
    Meaning: "ninth day of the month / 9 days",
  },
  {
    Kanji: "九つ",
    Vocabulary: "kokonotsu ここのつ",
    Type: "Noun, Numeric",
    Meaning: "nine; 9",
  },
  {
    Kanji: "困る",
    Vocabulary: "komaru こまる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to be troubled",
  },
  {
    Kanji: "今晩",
    Vocabulary: "konban こんばん",
    Type: "Noun",
    Meaning: "tonight; this evening",
  },
  {
    Kanji: "今月",
    Vocabulary: "kongetsu こんげつ",
    Type: "Noun",
    Meaning: "this month",
  },
  {
    Kanji: "こんな",
    Vocabulary: "konna",
    Type: "Pre-noun adjectival",
    Meaning: "such; like this​",
  },
  {
    Kanji: "この",
    Vocabulary: "kono",
    Type: "Pre-noun adjectival",
    Meaning: "this​",
  },
  {
    Kanji: "今週",
    Vocabulary: "konshuu こんし? う",
    Type: "Noun",
    Meaning: "this week",
  },
  {
    Kanji: "コーヒー",
    Vocabulary: "koohii",
    Type: "Noun, Katakana",
    Meaning: "Coffee",
  },
  {
    Kanji: "コート",
    Vocabulary: "kooto",
    Type: "Noun, Katakana",
    Meaning: "coat",
  },
  {
    Kanji: "コピー",
    Vocabulary: "kopii",
    Type: "Noun, Suru verb, Katakana",
    Meaning: "copy; photocopy",
  },
  {
    Kanji: "コップ",
    Vocabulary: "koppu",
    Type: "Noun, Katakana",
    Meaning: "glass (drinking vessel); tumbler​",
  },
  {
    Kanji: "これ",
    Vocabulary: "kore",
    Type: "Pronoun",
    Meaning: "this",
  },
  {
    Kanji: "答える",
    Vocabulary: "kotaeru こたえる",
    Type: "Verb, Ichidan verb, Intransitive verb",
    Meaning: "to answer",
  },
  {
    Kanji: "言葉",
    Vocabulary: "kotoba ことば",
    Type: "Noun",
    Meaning: "word; words",
  },
  {
    Kanji: "今年",
    Vocabulary: "kotoshi ことし",
    Type: "Noun",
    Meaning: "this year",
  },
  {
    Kanji: "交番",
    Vocabulary: "kouban こうばん",
    Type: "Noun",
    Meaning: "police box",
  },
  {
    Kanji: "紅茶",
    Vocabulary: "koucha こうちゃ",
    Type: "Noun",
    Meaning: "black tea",
  },
  {
    Kanji: "公園",
    Vocabulary: "kouen こうえん",
    Type: "Noun",
    Meaning: "park",
  },
  {
    Kanji: "交差点",
    Vocabulary: "kousaten こうさてん",
    Type: "Noun",
    Meaning: "intersection",
  },
  {
    Kanji: "口",
    Vocabulary: "kuchi くち",
    Type: "Noun",
    Meaning: "mouth, opening",
  },
  {
    Kanji: "果物",
    Vocabulary: "kudamono くだもの",
    Type: "Noun",
    Meaning: "fruit",
  },
  {
    Kanji: "下さい",
    Vocabulary: "kudasai ください",
    Type: "Expression",
    Meaning: "please",
  },
  {
    Kanji: "曇り",
    Vocabulary: "kumori くもり",
    Type: "Noun",
    Meaning: "cloudiness; cloudy weather",
  },
  {
    Kanji: "曇る",
    Vocabulary: "kumoru くもる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to become cloudy, to become dim",
  },
  {
    Kanji: "国",
    Vocabulary: "kuni くに",
    Type: "Noun",
    Meaning: "country; state; region",
  },
  {
    Kanji: "暗い",
    Vocabulary: "kurai くらい",
    Type: "Adjective, い-adjective",
    Meaning: "dark; gloomy; murky",
  },
  {
    Kanji: "クラス",
    Vocabulary: "kurasu",
    Type: "Noun, Katakana",
    Meaning: "class",
  },
  {
    Kanji: "黒",
    Vocabulary: "kuro くろ",
    Type: "Noun",
    Meaning: "black",
  },
  {
    Kanji: "黒い",
    Vocabulary: "kuroi くろい",
    Type: "い-adjective",
    Meaning: "black",
  },
  {
    Kanji: "来る",
    Vocabulary: "kuru くる",
    Type: "Verb, Intransitive verb",
    Meaning: "to come",
  },
  {
    Kanji: "車",
    Vocabulary: "kuruma くるま",
    Type: "Noun",
    Meaning: "car; automobile; vehicle",
  },
  {
    Kanji: "薬",
    Vocabulary: "kusuri くすり",
    Type: "Noun",
    Meaning: "medicine",
  },
  {
    Kanji: "靴",
    Vocabulary: "kutsu くつ",
    Type: "Noun",
    Meaning: "shoes",
  },
  {
    Kanji: "靴下",
    Vocabulary: "kutsushita くつした",
    Type: "Noun",
    Meaning: "socks",
  },
  {
    Kanji: "去年",
    Vocabulary: "kyonen きょねん",
    Type: "Noun",
    Meaning: "last year",
  },
  {
    Kanji: "今日",
    Vocabulary: "kyou きょう",
    Type: "Noun, Temporal noun",
    Meaning: "today; this day",
  },
  {
    Kanji: "兄弟",
    Vocabulary: "kyoudai きょうだい",
    Type: "Noun",
    Meaning: "siblings; brothers and sisters​; mate",
  },
  {
    Kanji: "教室",
    Vocabulary: "kyoushitsu きょうしつ",
    Type: "Noun",
    Meaning: "classroom",
  },
  {
    Kanji: "九",
    Vocabulary: "kyuu き? う",
    Type: "Noun, Numeric",
    Meaning: "nine; 9",
  },
  {
    Kanji: "マッチ",
    Vocabulary: "macchi",
    Type: "Noun, Katakana",
    Meaning: "match",
  },
  {
    Kanji: "町",
    Vocabulary: "machi まち",
    Type: "Noun",
    Meaning: "town; block; neighborhood",
  },
  {
    Kanji: "窓",
    Vocabulary: "mado まど",
    Type: "Noun",
    Meaning: "window",
  },
  {
    Kanji: "前",
    Vocabulary: "mae まえ",
    Type: "Noun, Suffix",
    Meaning: "previous; before; in front; ago",
  },
  {
    Kanji: "曲がる",
    Vocabulary: "magaru まがる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to turn, to bend",
  },
  {
    Kanji: "毎朝",
    Vocabulary: "maiasa まいあさ",
    Type: "Noun",
    Meaning: "every morning",
  },
  {
    Kanji: "毎晩",
    Vocabulary: "maiban まいばん",
    Type: "Noun",
    Meaning: "every night",
  },
  {
    Kanji: "毎日",
    Vocabulary: "mainichi まいにち",
    Type: "Noun",
    Meaning: "every day",
  },
  {
    Kanji: "毎週",
    Vocabulary: "maishuu まいし? う",
    Type: "Noun",
    Meaning: "every week",
  },
  {
    Kanji: "毎年",
    Vocabulary: "maitoshi/mainen まいとし / まいねん",
    Type: "Noun",
    Meaning: "every year; yearly; annually",
  },
  {
    Kanji: "毎月",
    Vocabulary: "maitsuki まいつき",
    Type: "Noun",
    Meaning: "every month; monthly",
  },
  {
    Kanji: "万",
    Vocabulary: "man まん",
    Type: "Noun, Numeric",
    Meaning: "10,000; ten thousand",
  },
  {
    Kanji: "万年筆",
    Vocabulary: "mannenhitsu まんねんひつ",
    Type: "Noun",
    Meaning: "fountain pen",
  },
  {
    Kanji: "丸い",
    Vocabulary: "marui まるい",
    Type: "Adjective, い-adjective",
    Meaning: "round,circular",
  },
  {
    Kanji: "真っ直ぐ",
    Vocabulary: "massugu まっすぐ",
    Type: "Noun, Adjective, な-adjective, Adverb",
    Meaning: "straight ahead,direct",
  },
  {
    Kanji: "待つ",
    Vocabulary: "matsu まつ",
    Type: "Verb, Godan verb, Intransitive verb, Transitive verb",
    Meaning: "to wait​",
  },
  {
    Kanji: "不味い",
    Vocabulary: "mazui まずい",
    Type: "Adjective, い-adjective",
    Meaning: "unpleasant",
  },
  {
    Kanji: "目",
    Vocabulary: "me め",
    Type: "Noun",
    Meaning: "eye",
  },
  {
    Kanji: "メートル",
    Vocabulary: "meetoru",
    Type: "Noun, Katakana",
    Meaning: "metre; meter",
  },
  {
    Kanji: "眼鏡",
    Vocabulary: "megane めがね",
    Type: "Noun",
    Meaning: "glasses",
  },
  {
    Kanji: "道",
    Vocabulary: "michi みち",
    Type: "Noun",
    Meaning: "road; street",
  },
  {
    Kanji: "緑",
    Vocabulary: "midori みどり",
    Type: "Noun",
    Meaning: "green",
  },
  {
    Kanji: "磨く",
    Vocabulary: "migaku みがく",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to polish; to shine; to brush (e.g. teeth)",
  },
  {
    Kanji: "右",
    Vocabulary: "migi みぎ",
    Type: "Noun",
    Meaning: "right; right hand side",
  },
  {
    Kanji: "短い",
    Vocabulary: "mijikai みじかい",
    Type: "Adjective, い-adjective",
    Meaning: "short",
  },
  {
    Kanji: "三日",
    Vocabulary: "mikka みっか",
    Type: "Noun",
    Meaning: "the third day of the month / 3 days",
  },
  {
    Kanji: "耳",
    Vocabulary: "mimi みみ",
    Type: "Noun",
    Meaning: "ear; hearing",
  },
  {
    Kanji: "南",
    Vocabulary: "minami みなみ",
    Type: "Noun",
    Meaning: "south",
  },
  {
    Kanji: "皆さん",
    Vocabulary: "minasan みなさん",
    Type: "Noun",
    Meaning: "everyone",
  },
  {
    Kanji: "みんな",
    Vocabulary: "minna",
    Type: "Noun, Adverb",
    Meaning: "all; everyone; everybody",
  },
  {
    Kanji: "見る",
    Vocabulary: "miru みる",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to see; to look; to watch; to view; to observe",
  },
  {
    Kanji: "店",
    Vocabulary: "mise みせ",
    Type: "Noun",
    Meaning: "store; shop; establishment; restaurant",
  },
  {
    Kanji: "見せる",
    Vocabulary: "miseru みせる",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to show; to display",
  },
  {
    Kanji: "三つ",
    Vocabulary: "mitsu みつ",
    Type: "Noun, Numeric",
    Meaning: "three; 3",
  },
  {
    Kanji: "水",
    Vocabulary: "mizu みず",
    Type: "Noun",
    Meaning: "water; fluid; liquid​",
  },
  {
    Kanji: "木曜日",
    Vocabulary: "mokuyoubi もくようび",
    Type: "Noun",
    Meaning: "Thursday",
  },
  {
    Kanji: "門",
    Vocabulary: "mon もん",
    Type: "Noun",
    Meaning: "gate",
  },
  {
    Kanji: "問題",
    Vocabulary: "mondai もんだい",
    Type: "Noun",
    Meaning: "problem; question (e.g. on a test)",
  },
  {
    Kanji: "物",
    Vocabulary: "mono もの",
    Type: "Noun",
    Meaning: "thing",
  },
  {
    Kanji: "持つ",
    Vocabulary: "motsu もつ",
    Type: "Verb, Godan verb",
    Meaning: "to hold",
  },
  {
    Kanji: "もっと",
    Vocabulary: "motto",
    Type: "Adverb",
    Meaning: "more; longer; further",
  },
  {
    Kanji: "もう一度",
    Vocabulary: "mouichido もういちど",
    Type: "Expression",
    Meaning: "once more; again",
  },
  {
    Kanji: "六日",
    Vocabulary: "muika むいか",
    Type: "Noun",
    Meaning: "sixth day of the month / 6 days",
  },
  {
    Kanji: "向こう",
    Vocabulary: "mukou むこう",
    Type: "Noun",
    Meaning: "over there",
  },
  {
    Kanji: "村",
    Vocabulary: "mura むら",
    Type: "Noun",
    Meaning: "village",
  },
  {
    Kanji: "六つ",
    Vocabulary: "muttsu むっつ",
    Type: "Noun, Numeric",
    Meaning: "six; 6",
  },
  {
    Kanji: "難しい",
    Vocabulary: "muzukashii むずかしい",
    Type: "Adjective, い-adjective",
    Meaning: "difficult",
  },
  {
    Kanji: "長い",
    Vocabulary: "nagai ながい",
    Type: "Adjective, い-adjective",
    Meaning: "long (distance)​;  long (time); lengthy.",
  },
  {
    Kanji: "ナイフ",
    Vocabulary: "naifu",
    Type: "Noun, Katakana",
    Meaning: "knife",
  },
  {
    Kanji: "中",
    Vocabulary: "naka なか",
    Type: "Noun",
    Meaning: "inside; in; within; center",
  },
  {
    Kanji: "鳴く",
    Vocabulary: "naku なく",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "animal noise. to chirp",
  },
  {
    Kanji: "無くす",
    Vocabulary: "nakusu なくす",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to lose (something)",
  },
  {
    Kanji: "名前",
    Vocabulary: "namae なまえ",
    Type: "Noun",
    Meaning: "name; full name; given name",
  },
  {
    Kanji: "七つ",
    Vocabulary: "nanatsu ななつ",
    Type: "Noun, Numeric",
    Meaning: "seven; 7",
  },
  {
    Kanji: "何",
    Vocabulary: "nani なに",
    Type: "Noun, Pronoun, Prefix",
    Meaning: "what",
  },
  {
    Kanji: "七日",
    Vocabulary: "nanoka なのか",
    Type: "Noun",
    Meaning: "seventh day of the month / 7 days",
  },
  {
    Kanji: "並べる",
    Vocabulary: "naraberu ならべる",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to line up,to set up",
  },
  {
    Kanji: "並ぶ",
    Vocabulary: "narabu ならぶ",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to line up,to stand in a line",
  },
  {
    Kanji: "習う",
    Vocabulary: "narau ならう",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to be taught; to learn (from a teacher)",
  },
  {
    Kanji: "夏",
    Vocabulary: "natsu なつ",
    Type: "Noun",
    Meaning: "summer",
  },
  {
    Kanji: "夏休み",
    Vocabulary: "natsuyasumi なつやすみ",
    Type: "Noun",
    Meaning: "summer vacation; summer holiday",
  },
  {
    Kanji: "何故",
    Vocabulary: "naze なぜ",
    Type: "Adverb",
    Meaning: "why; how",
  },
  {
    Kanji: "猫",
    Vocabulary: "neko ねこ",
    Type: "Noun",
    Meaning: "cat",
  },
  {
    Kanji: "ネクタイ",
    Vocabulary: "nekutai",
    Type: "Noun, Katakana",
    Meaning: "tie; necktie",
  },
  {
    Kanji: "寝る",
    Vocabulary: "neru ねる",
    Type: "Verb, Ichidan verb, Intransitive verb",
    Meaning: "to sleep; to go to bed; to lie down",
  },
  {
    Kanji: "二",
    Vocabulary: "ni に",
    Type: "Noun, Numeric",
    Meaning: "two; 2",
  },
  {
    Kanji: "日曜日",
    Vocabulary: "nichiyoubi にちようび",
    Type: "Noun",
    Meaning: "Sunday",
  },
  {
    Kanji: "賑やか",
    Vocabulary: "nigiyaka にぎやか",
    Type: "Adjective, な-adjective",
    Meaning: "bustling,busy",
  },
  {
    Kanji: "日記",
    Vocabulary: "nikki にっき",
    Type: "Noun",
    Meaning: "diary; journal",
  },
  {
    Kanji: "肉",
    Vocabulary: "niku にく",
    Type: "Noun",
    Meaning: "meat",
  },
  {
    Kanji: "荷物",
    Vocabulary: "nimotsu にもつ",
    Type: "Noun",
    Meaning: "luggage; baggage",
  },
  {
    Kanji: "西",
    Vocabulary: "nishi にし",
    Type: "Noun",
    Meaning: "west",
  },
  {
    Kanji: "庭",
    Vocabulary: "niwa にわ",
    Type: "Noun",
    Meaning: "garden",
  },
  {
    Kanji: "登る",
    Vocabulary: "noboru のぼる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to climb",
  },
  {
    Kanji: "飲み物",
    Vocabulary: "nomimono のみもの",
    Type: "Noun",
    Meaning: "drink; beverage",
  },
  {
    Kanji: "飲む",
    Vocabulary: "nomu のむ",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to drink",
  },
  {
    Kanji: "ノート",
    Vocabulary: "nooto",
    Type: "Noun, Katakana",
    Meaning: "notebook",
  },
  {
    Kanji: "乗る",
    Vocabulary: "noru のる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to get on (train, plane, bus, ship, etc.)",
  },
  {
    Kanji: "脱ぐ",
    Vocabulary: "nugu ぬぐ",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to take off clothes",
  },
  {
    Kanji: "温い",
    Vocabulary: "nurui ぬるい",
    Type: "Adjective, い-adjective",
    Meaning: "luke warm",
  },
  {
    Kanji: "ニュース",
    Vocabulary: "nyuusu",
    Type: "Noun, Katakana",
    Meaning: "news",
  },
  {
    Kanji: "おばあさん",
    Vocabulary: "obaasan",
    Type: "Noun",
    Meaning: "grandmother",
  },
  {
    Kanji: "伯母さん",
    Vocabulary: "obasan おばさん",
    Type: "Noun",
    Meaning: "aunt; old lady",
  },
  {
    Kanji: "お弁当",
    Vocabulary: "obentou おべんとう",
    Type: "Noun",
    Meaning: "lunch box; Japanese box lunch",
  },
  {
    Kanji: "覚える",
    Vocabulary: "oboeru おぼえる",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to remember",
  },
  {
    Kanji: "お茶",
    Vocabulary: "ocha おちゃ",
    Type: "Noun",
    Meaning: "tea",
  },
  {
    Kanji: "お風呂",
    Vocabulary: "ofuro おふろ",
    Type: "Noun",
    Meaning: "bath",
  },
  {
    Kanji: "美味しい",
    Vocabulary: "oishii おいしい",
    Type: "い-adjective",
    Meaning: "delicious",
  },
  {
    Kanji: "伯父さん",
    Vocabulary: "ojisan おじさん",
    Type: "Noun",
    Meaning: "uncle; old man; mister",
  },
  {
    Kanji: "お母さん",
    Vocabulary: "okaasan おかあさん",
    Type: "Noun",
    Meaning: "mother; mom; mum; ma",
  },
  {
    Kanji: "お金",
    Vocabulary: "okane おかね",
    Type: "Noun",
    Meaning: "money",
  },
  {
    Kanji: "お菓子",
    Vocabulary: "okashi おかし",
    Type: "Noun",
    Meaning: "confections; sweets; candy",
  },
  {
    Kanji: "起きる",
    Vocabulary: "okiru おきる",
    Type: "Verb, Ichidan verb, Intransitive verb",
    Meaning: "to get up; to wake up",
  },
  {
    Kanji: "置く",
    Vocabulary: "oku おく",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to put; to place​",
  },
  {
    Kanji: "奥さん",
    Vocabulary: "okusan おくさん",
    Type: "Noun",
    Meaning: "wife; your wife; his wife",
  },
  {
    Kanji: "お巡りさん",
    Vocabulary: "omawari-san おまわりさん",
    Type: "Noun",
    Meaning: "police officer (friendly term for policeman)",
  },
  {
    Kanji: "重い",
    Vocabulary: "omoi おもい",
    Type: "い-adjective",
    Meaning: "heavy",
  },
  {
    Kanji: "面白い",
    Vocabulary: "omoshiroi おもしろい",
    Type: "Adjective, い-adjective",
    Meaning: "interesting",
  },
  {
    Kanji: "同じ",
    Vocabulary: "onaji おなじ",
    Type: "Noun, Adverb",
    Meaning: "same",
  },
  {
    Kanji: "お腹",
    Vocabulary: "onaka おなか",
    Type: "Noun",
    Meaning: "stomach",
  },
  {
    Kanji: "お姉さん",
    Vocabulary: "oneesan おねえさん",
    Type: "Noun",
    Meaning: "elder sister; young lady; miss; ma'am",
  },
  {
    Kanji: "音楽",
    Vocabulary: "ongaku おんがく",
    Type: "Noun",
    Meaning: "music",
  },
  {
    Kanji: "お兄さん",
    Vocabulary: "oniisan おにいさん",
    Type: "Noun",
    Meaning: "older brother; elder brother; young man; buddy",
  },
  {
    Kanji: "女",
    Vocabulary: "onna おんな",
    Type: "Noun, Prefix",
    Meaning: "woman; female sex",
  },
  {
    Kanji: "女の子",
    Vocabulary: "onnanoko おんなのこ",
    Type: "Noun, Expression",
    Meaning: "girl; daughter; young women",
  },
  {
    Kanji: "多い",
    Vocabulary: "ooi おおい",
    Type: "Adjective, い-adjective",
    Meaning: "many; numerous; a lot; large quantity; frequent",
  },
  {
    Kanji: "大きい",
    Vocabulary: "ookii おおきい",
    Type: "Adjective, い-adjective",
    Meaning: "big; large; great; important",
  },
  {
    Kanji: "大きな",
    Vocabulary: "ookina おおきな",
    Type: "Pre-noun adjectival",
    Meaning: "big; large; great​",
  },
  {
    Kanji: "大勢",
    Vocabulary: "oozei おおぜい",
    Type: "Noun",
    Meaning: "crowd of people; great number of people",
  },
  {
    Kanji: "降りる",
    Vocabulary: "oriru おりる",
    Type: "Verb, Ichidan verb, Intransitive verb",
    Meaning: "to get off",
  },
  {
    Kanji: "お酒",
    Vocabulary: "osake おさけ",
    Type: "Noun",
    Meaning: "alcohol",
  },
  {
    Kanji: "お皿",
    Vocabulary: "osara おさら",
    Type: "Noun",
    Meaning: "plate, dish",
  },
  {
    Kanji: "教える",
    Vocabulary: "oshieru おしえる",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to teach",
  },
  {
    Kanji: "遅い",
    Vocabulary: "osoi おそい",
    Type: "Adjective, い-adjective",
    Meaning: "slow; time-consuming; late",
  },
  {
    Kanji: "押す",
    Vocabulary: "osu おす",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to push; to press​",
  },
  {
    Kanji: "お手洗い",
    Vocabulary: "otearai おてあらい",
    Type: "Noun",
    Meaning: "toilet; restroom; lavatory; bathroom",
  },
  {
    Kanji: "男",
    Vocabulary: "otoko おとこ",
    Type: "Noun",
    Meaning: "man; male",
  },
  {
    Kanji: "男の子",
    Vocabulary: "otokonoko おとこのこ",
    Type: "Noun, Expression",
    Meaning: "boy; male child; baby boy",
  },
  {
    Kanji: "大人",
    Vocabulary: "otona おとな",
    Type: "Noun",
    Meaning: "adult",
  },
  {
    Kanji: "一昨日",
    Vocabulary: "ototoi おととい",
    Type: "Noun",
    Meaning: "day before yesterday",
  },
  {
    Kanji: "一昨年",
    Vocabulary: "ototoshi おととし",
    Type: "Noun",
    Meaning: "year before last",
  },
  {
    Kanji: "お父さん",
    Vocabulary: "otousan おとうさん",
    Type: "Noun",
    Meaning: "father; dad; papa; pa; pop; daddy",
  },
  {
    Kanji: "弟",
    Vocabulary: "otouto おとうと",
    Type: "Noun",
    Meaning: "younger brother",
  },
  {
    Kanji: "終る",
    Vocabulary: "owaru おわる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to finish; to end",
  },
  {
    Kanji: "泳ぐ",
    Vocabulary: "oyogu およぐ",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to swim",
  },
  {
    Kanji: "パーティー",
    Vocabulary: "paatii",
    Type: "Noun, Katakana",
    Meaning: "party",
  },
  {
    Kanji: "パン",
    Vocabulary: "pan",
    Type: "Noun, Katakana",
    Meaning: "bread",
  },
  {
    Kanji: "ページ",
    Vocabulary: "peeji",
    Type: "Noun, Katakana",
    Meaning: "page",
  },
  {
    Kanji: "ペン",
    Vocabulary: "pen",
    Type: "Noun, Katakana",
    Meaning: "pen",
  },
  {
    Kanji: "ペット",
    Vocabulary: "petto",
    Type: "Noun, Katakana",
    Meaning: "pet",
  },
  {
    Kanji: "ポケット",
    Vocabulary: "poketto",
    Type: "Noun",
    Meaning: "pocket",
  },
  {
    Kanji: "ポスト",
    Vocabulary: "posuto",
    Type: "Noun, Katakana",
    Meaning: "post",
  },
  {
    Kanji: "プール",
    Vocabulary: "puuru",
    Type: "Noun, Katakana",
    Meaning: "swimming pool",
  },
  {
    Kanji: "来月",
    Vocabulary: "raigetsu らいげつ",
    Type: "Noun",
    Meaning: "next month",
  },
  {
    Kanji: "来年",
    Vocabulary: "rainen らいねん",
    Type: "Noun",
    Meaning: "next year",
  },
  {
    Kanji: "来週",
    Vocabulary: "raishuu らいし? う",
    Type: "Noun",
    Meaning: "next week",
  },
  {
    Kanji: "ラジオ",
    Vocabulary: "rajiio",
    Type: "Noun, Katakana",
    Meaning: "radio",
  },
  {
    Kanji: "零",
    Vocabulary: "reiれい",
    Type: "Noun",
    Meaning: "zero",
  },
  {
    Kanji: "冷蔵庫",
    Vocabulary: "reizouko れいぞうこ",
    Type: "Noun",
    Meaning: "refrigerator",
  },
  {
    Kanji: "レコード",
    Vocabulary: "rekoodo",
    Type: "Noun, Katakana",
    Meaning: "record",
  },
  {
    Kanji: "練習",
    Vocabulary: "renshuu れんし? う",
    Type: "Noun, Verb, Suru verb",
    Meaning: "practice; practicing",
  },
  {
    Kanji: "レストラン",
    Vocabulary: "resutoran",
    Type: "Noun, Katakana",
    Meaning: "restaurant",
  },
  {
    Kanji: "立派",
    Vocabulary: "rippa りっぱ",
    Type: "Adjective, な-adjective",
    Meaning: "splendid",
  },
  {
    Kanji: "六",
    Vocabulary: "roku ろく",
    Type: "Noun, Numeric",
    Meaning: "six; 6",
  },
  {
    Kanji: "廊下",
    Vocabulary: "rouka ろうか",
    Type: "Noun",
    Meaning: "corridor; hallway; passageway",
  },
  {
    Kanji: "旅行",
    Vocabulary: "ryokou りょこう",
    Type: "Noun, Verb, Suru verb",
    Meaning: "travel; trip; journey; excursion; tour",
  },
  {
    Kanji: "料理",
    Vocabulary: "ryouri りょうり",
    Type: "Noun, Suru verb",
    Meaning: "cuisine",
  },
  {
    Kanji: "両親",
    Vocabulary: "ryoushin りょうしん",
    Type: "Noun",
    Meaning: "parents; both parents",
  },
  {
    Kanji: "留学生",
    Vocabulary: "ryuugakusei り? うがくせい",
    Type: "Noun",
    Meaning: "overseas student; exchange student",
  },
  {
    Kanji: "さあ",
    Vocabulary: "saa",
    Type: "Conjunction",
    Meaning: "well…",
  },
  {
    Kanji: "財布",
    Vocabulary: "saifu さいふ",
    Type: "Noun",
    Meaning: "purse; wallet",
  },
  {
    Kanji: "魚",
    Vocabulary: "sakana さかな",
    Type: "Noun",
    Meaning: "fish",
  },
  {
    Kanji: "先",
    Vocabulary: "saki さき",
    Type: "Noun, Prefix, Suffix",
    Meaning: "previous; prior; first; earlier",
  },
  {
    Kanji: "咲く",
    Vocabulary: "saku さく",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to bloom",
  },
  {
    Kanji: "作文",
    Vocabulary: "sakubun さくぶん",
    Type: "Noun",
    Meaning: "writing; composition",
  },
  {
    Kanji: "寒い",
    Vocabulary: "samui さむい",
    Type: "Adjective, い-adjective",
    Meaning: "cold",
  },
  {
    Kanji: "三",
    Vocabulary: "san さん",
    Type: "Noun, Numeric",
    Meaning: "three; 3",
  },
  {
    Kanji: "散歩",
    Vocabulary: "sanpo さんぽ",
    Type: "Noun, Verb, Suru verb",
    Meaning: "walk; stroll",
  },
  {
    Kanji: "再来年",
    Vocabulary: "sarainen さらいねん",
    Type: "Noun",
    Meaning: "year after next",
  },
  {
    Kanji: "差す",
    Vocabulary: "sasu さす",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to stretch out hands, to raise an umbrella",
  },
  {
    Kanji: "砂糖",
    Vocabulary: "satou さとう",
    Type: "Noun",
    Meaning: "sugar",
  },
  {
    Kanji: "背",
    Vocabulary: "se せ",
    Type: "Noun",
    Meaning: "height; stature; back; spine",
  },
  {
    Kanji: "背広",
    Vocabulary: "sebiro せびろ",
    Type: "Noun",
    Meaning: "business suit",
  },
  {
    Kanji: "セーター",
    Vocabulary: "seetaa",
    Type: "Noun, Katakana",
    Meaning: "sweater; jumper",
  },
  {
    Kanji: "生徒",
    Vocabulary: "seito せいと",
    Type: "Noun",
    Meaning: "pupil; student",
  },
  {
    Kanji: "石鹼",
    Vocabulary: "sekken せっけん",
    Type: "Noun",
    Meaning: "soap",
  },
  {
    Kanji: "狭い",
    Vocabulary: "semai せまい",
    Type: "い-adjective",
    Meaning: "narrow",
  },
  {
    Kanji: "千",
    Vocabulary: "sen せん",
    Type: "Noun, Numeric",
    Meaning: "1,000; thousand",
  },
  {
    Kanji: "先月",
    Vocabulary: "sengetsu せんげつ",
    Type: "Noun",
    Meaning: "last month",
  },
  {
    Kanji: "先生",
    Vocabulary: "sensei せんせい",
    Type: "Noun, Suffix",
    Meaning: "teacher; instructor; master",
  },
  {
    Kanji: "先週",
    Vocabulary: "senshuu せんし? う",
    Type: "Noun",
    Meaning: "last week",
  },
  {
    Kanji: "洗濯",
    Vocabulary: "sentaku せんたく",
    Type: "Noun, Suru verb",
    Meaning: "washing; laundry",
  },
  {
    Kanji: "写真",
    Vocabulary: "shashin しゃしん",
    Type: "Noun",
    Meaning: "photograph; photo",
  },
  {
    Kanji: "シャツ",
    Vocabulary: "shatsu",
    Type: "Noun, Katakana",
    Meaning: "shirt",
  },
  {
    Kanji: "シャワー",
    Vocabulary: "shawaa",
    Type: "Noun, Katakana",
    Meaning: "shower",
  },
  {
    Kanji: "四",
    Vocabulary: "shi し",
    Type: "Noun, Numeric",
    Meaning: "four; 4",
  },
  {
    Kanji: "七",
    Vocabulary: "shichi しち",
    Type: "Noun, Numeric",
    Meaning: "seven; 7",
  },
  {
    Kanji: "仕事",
    Vocabulary: "shigoto しごと",
    Type: "Noun, Verb, Suru verb",
    Meaning: "work; job; business",
  },
  {
    Kanji: "閉まる",
    Vocabulary: "shimaru しまる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to close, to be closed",
  },
  {
    Kanji: "締める",
    Vocabulary: "shimeru しめる",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to tie; to fasten; to tighten​",
  },
  {
    Kanji: "閉める",
    Vocabulary: "shimeru しめる",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to close; to shut",
  },
  {
    Kanji: "新聞",
    Vocabulary: "shinbun しんぶん",
    Type: "Noun",
    Meaning: "newspaper",
  },
  {
    Kanji: "死ぬ",
    Vocabulary: "shinu しぬ",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to die",
  },
  {
    Kanji: "塩",
    Vocabulary: "shio しお",
    Type: "Noun",
    Meaning: "salt",
  },
  {
    Kanji: "白",
    Vocabulary: "shiro しろ",
    Type: "Noun",
    Meaning: "white; innocence; innocent person",
  },
  {
    Kanji: "白い",
    Vocabulary: "shiroi しろい",
    Type: "Adjective, い-adjective",
    Meaning: "white",
  },
  {
    Kanji: "知る",
    Vocabulary: "shiru しる",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to know",
  },
  {
    Kanji: "下",
    Vocabulary: "shita した",
    Type: "Noun",
    Meaning: "below; down; under; bottom",
  },
  {
    Kanji: "質問",
    Vocabulary: "shitsumon しつもん",
    Type: "Noun, Verb, Suru verb",
    Meaning: "question; inquiry",
  },
  {
    Kanji: "静か",
    Vocabulary: "shizuka しずか",
    Type: "Adjective, な-adjective",
    Meaning: "quiet",
  },
  {
    Kanji: "食堂",
    Vocabulary: "shokudou しょくどう",
    Type: "Noun",
    Meaning: "cafeteria; dining room",
  },
  {
    Kanji: "醬油",
    Vocabulary: "shouyu しょうゆ",
    Type: "Noun",
    Meaning: "soy sauce",
  },
  {
    Kanji: "宿題",
    Vocabulary: "shukudai し? くだい",
    Type: "Noun",
    Meaning: "homework; assignment; pending issue",
  },
  {
    Kanji: "そば",
    Vocabulary: "soba",
    Type: "Noun",
    Meaning: "near; beside",
  },
  {
    Kanji: "そっち",
    Vocabulary: "socchi",
    Type: "Pronoun",
    Meaning: "that way; ​over there",
  },
  {
    Kanji: "そちら",
    Vocabulary: "sochira",
    Type: "Pronoun",
    Meaning: "that way (distant from speaker, close to listener); you; your family",
  },
  {
    Kanji: "そこ",
    Vocabulary: "soko",
    Type: "Pronoun",
    Meaning: "that place​; there",
  },
  {
    Kanji: "その",
    Vocabulary: "sono",
    Type: "Pre-noun adjectival",
    Meaning: "that",
  },
  {
    Kanji: "空",
    Vocabulary: "sora そら",
    Type: "Noun",
    Meaning: "sky; the air",
  },
  {
    Kanji: "それ",
    Vocabulary: "sore",
    Type: "Pronoun",
    Meaning: "that",
  },
  {
    Kanji: "それでは",
    Vocabulary: "sore-dewa",
    Type: "Expression",
    Meaning: "in that situation",
  },
  {
    Kanji: "外",
    Vocabulary: "soto そと",
    Type: "Noun",
    Meaning: "outside; exterior;",
  },
  {
    Kanji: "掃除",
    Vocabulary: "souji そうじ",
    Type: "Noun, Suru verb",
    Meaning: "to clean, to sweep",
  },
  {
    Kanji: "直ぐに",
    Vocabulary: "sugu-ni すぐに",
    Type: "Adverb",
    Meaning: "immediately; right away; instantly​",
  },
  {
    Kanji: "水曜日",
    Vocabulary: "suiyoubi すいようび",
    Type: "Noun",
    Meaning: "Wednesday",
  },
  {
    Kanji: "スカート",
    Vocabulary: "sukaato",
    Type: "Noun, Katakana",
    Meaning: "skirt",
  },
  {
    Kanji: "好き",
    Vocabulary: "suki すき",
    Type: "Noun, Adjective, な-adjective",
    Meaning: "like",
  },
  {
    Kanji: "少し",
    Vocabulary: "sukoshi すこし",
    Type: "Noun, Adverb",
    Meaning: "a little (bit); small quantity; few; short distance",
  },
  {
    Kanji: "少ない",
    Vocabulary: "sukunai すくない",
    Type: "い-adjective",
    Meaning: "few; a little; scarce; insufficient; seldom",
  },
  {
    Kanji: "住む",
    Vocabulary: "sumu すむ",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to live in; to reside; to inhabit; to dwell; to abide",
  },
  {
    Kanji: "スポーツ",
    Vocabulary: "supootsu",
    Type: "Noun, Katakana",
    Meaning: "sport; sports",
  },
  {
    Kanji: "スプーン",
    Vocabulary: "supuun",
    Type: "Noun, Katakana",
    Meaning: "spoon",
  },
  {
    Kanji: "スリッパ",
    Vocabulary: "surippa",
    Type: "Noun, Katakana",
    Meaning: "slipper; slippers",
  },
  {
    Kanji: "ストーブ",
    Vocabulary: "sutoobu",
    Type: "Noun, Katakana",
    Meaning: "heater; stove",
  },
  {
    Kanji: "吸う",
    Vocabulary: "suu すう",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to smoke, to suck",
  },
  {
    Kanji: "座る",
    Vocabulary: "suwaru すわる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to sit",
  },
  {
    Kanji: "涼しい",
    Vocabulary: "suzushii すずしい",
    Type: "Adjective, い-adjective",
    Meaning: "refreshing, cool",
  },
  {
    Kanji: "たばこ",
    Vocabulary: "tabako",
    Type: "Noun",
    Meaning: "tobacco; cigarette",
  },
  {
    Kanji: "食べ物",
    Vocabulary: "tabemono たべもの",
    Type: "Noun",
    Meaning: "food",
  },
  {
    Kanji: "食べる",
    Vocabulary: "taberu たべる",
    Type: "Verb, Ichidan verb, Intransitive verb",
    Meaning: "to eat",
  },
  {
    Kanji: "多分",
    Vocabulary: "tabun たぶん",
    Type: "Adjective, な-adjective, Adverb",
    Meaning: "perhaps; probably",
  },
  {
    Kanji: "大変",
    Vocabulary: "taihen たいへん",
    Type: "Noun, Adjective, な-adjective, Adverb",
    Meaning: "very; greatly; terribly; serious; difficult",
  },
  {
    Kanji: "大切",
    Vocabulary: "taisetsu たいせつ",
    Type: "Noun, Adjective, な-adjective",
    Meaning: "important; necessary; indispensable; beloved",
  },
  {
    Kanji: "大使館",
    Vocabulary: "taishikan たいしかん",
    Type: "Noun",
    Meaning: "embassy",
  },
  {
    Kanji: "高い",
    Vocabulary: "takai たかい",
    Type: "Adjective, い-adjective",
    Meaning: "high; tall; expensive; above average",
  },
  {
    Kanji: "沢山",
    Vocabulary: "takusan たくさん",
    Type: "Noun, Adverbial Noun, Adjective, な-adjective",
    Meaning: "many",
  },
  {
    Kanji: "タクシー",
    Vocabulary: "takushii",
    Type: "Noun, Katakana",
    Meaning: "taxi",
  },
  {
    Kanji: "卵",
    Vocabulary: "tamago たまご",
    Type: "Noun",
    Meaning: "eggs; egg",
  },
  {
    Kanji: "誕生日",
    Vocabulary: "tanjoubi たんじょうび",
    Type: "Noun",
    Meaning: "birthday",
  },
  {
    Kanji: "頼む",
    Vocabulary: "tanomu たのむ",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to ask",
  },
  {
    Kanji: "楽しい",
    Vocabulary: "tanoshii たのしい",
    Type: "Adjective, い-adjective",
    Meaning: "enjoyable; fun",
  },
  {
    Kanji: "縦",
    Vocabulary: "tate たて",
    Type: "Noun",
    Meaning: "length,height",
  },
  {
    Kanji: "建物",
    Vocabulary: "tatemono たてもの",
    Type: "Noun",
    Meaning: "building",
  },
  {
    Kanji: "立つ",
    Vocabulary: "tatsu たつ",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to stand; to stand up​",
  },
  {
    Kanji: "手",
    Vocabulary: "te て",
    Type: "Noun",
    Meaning: "hand; arm",
  },
  {
    Kanji: "テーブル",
    Vocabulary: "teeburu",
    Type: "Noun, Katakana",
    Meaning: "table",
  },
  {
    Kanji: "テープ",
    Vocabulary: "teepu",
    Type: "Noun, Katakana",
    Meaning: "tape",
  },
  {
    Kanji: "テープレコーダー",
    Vocabulary: "teepu-rekoodaa",
    Type: "Noun, Katakana",
    Meaning: "tape recorder",
  },
  {
    Kanji: "手紙",
    Vocabulary: "tegami てがみ",
    Type: "Noun",
    Meaning: "Letter (message)​",
  },
  {
    Kanji: "天気",
    Vocabulary: "tenki てんき",
    Type: "Noun",
    Meaning: "weather; the elements",
  },
  {
    Kanji: "テレビ",
    Vocabulary: "terebi",
    Type: "Noun, Katakana",
    Meaning: "television; TV​",
  },
  {
    Kanji: "テスト",
    Vocabulary: "tesuto",
    Type: "Noun, Suru verb, Katakana",
    Meaning: "examination; quiz; test",
  },
  {
    Kanji: "戸",
    Vocabulary: "toと",
    Type: "Noun",
    Meaning: "Japanese style door",
  },
  {
    Kanji: "飛ぶ",
    Vocabulary: "tobu とぶ",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to fly; to hop",
  },
  {
    Kanji: "トイレ",
    Vocabulary: "toire",
    Type: "Noun, Katakana",
    Meaning: "toilet",
  },
  {
    Kanji: "時計",
    Vocabulary: "tokei とけい",
    Type: "Noun",
    Meaning: "watch; clock; timepiece",
  },
  {
    Kanji: "時",
    Vocabulary: "toki とき",
    Type: "Noun",
    Meaning: "time; moment; occasion; chance",
  },
  {
    Kanji: "時々",
    Vocabulary: "tokidoki ときどき",
    Type: "Noun, Adverb",
    Meaning: "sometimes; at times",
  },
  {
    Kanji: "所",
    Vocabulary: "tokoro ところ",
    Type: "Noun, Suffix",
    Meaning: "place",
  },
  {
    Kanji: "止まる",
    Vocabulary: "tomaru とまる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to stop; to come to a halt",
  },
  {
    Kanji: "友達",
    Vocabulary: "tomodachi ともだち",
    Type: "Noun",
    Meaning: "friend; companion",
  },
  {
    Kanji: "隣",
    Vocabulary: "tonari となり",
    Type: "Noun",
    Meaning: "next door to",
  },
  {
    Kanji: "遠い",
    Vocabulary: "tooi とおい",
    Type: "Adjective, い-adjective",
    Meaning: "far",
  },
  {
    Kanji: "十日",
    Vocabulary: "tooka とおか",
    Type: "Noun",
    Meaning: "tenth day of the month / 10 days",
  },
  {
    Kanji: "鳥",
    Vocabulary: "tori とり",
    Type: "Noun",
    Meaning: "bird",
  },
  {
    Kanji: "鶏肉",
    Vocabulary: "toriniku とりにく",
    Type: "Noun",
    Meaning: "chicken meat",
  },
  {
    Kanji: "撮る",
    Vocabulary: "toru とる",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to take a photo or record a film",
  },
  {
    Kanji: "取る",
    Vocabulary: "toru とる",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to take; to pick up; to harvest; to earn; to win; to choose",
  },
  {
    Kanji: "年",
    Vocabulary: "toshi とし",
    Type: "Noun",
    Meaning: "year; age",
  },
  {
    Kanji: "図書館",
    Vocabulary: "toshokan としょかん",
    Type: "Noun",
    Meaning: "library",
  },
  {
    Kanji: "次",
    Vocabulary: "tsugi つぎ",
    Type: "Noun",
    Meaning: "next",
  },
  {
    Kanji: "一日",
    Vocabulary: "tsuitachi ついたち",
    Type: "Noun",
    Meaning: "first day of the month",
  },
  {
    Kanji: "疲れる",
    Vocabulary: "tsukareru つかれる",
    Type: "Verb, Ichidan verb, Intransitive verb",
    Meaning: "to get tired",
  },
  {
    Kanji: "使う",
    Vocabulary: "tsukau つかう",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to use",
  },
  {
    Kanji: "つける",
    Vocabulary: "tsukeru",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to turn on",
  },
  {
    Kanji: "着く",
    Vocabulary: "tsuku つく",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to arrive at",
  },
  {
    Kanji: "机",
    Vocabulary: "tsukue つくえ",
    Type: "Noun",
    Meaning: "desk",
  },
  {
    Kanji: "作る",
    Vocabulary: "tsukuru つくる",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to make",
  },
  {
    Kanji: "詰まらない",
    Vocabulary: "tsumaranai つまらない",
    Type: "Adjective, い-adjective",
    Meaning: "boring",
  },
  {
    Kanji: "冷たい",
    Vocabulary: "tsumetai つめたい",
    Type: "い-adjective",
    Meaning: "cold to the touch",
  },
  {
    Kanji: "勤める",
    Vocabulary: "tsutomeru つとめる",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to work for someone",
  },
  {
    Kanji: "強い",
    Vocabulary: "tsuyoi つよい",
    Type: "Adjective, い-adjective",
    Meaning: "powerful",
  },
  {
    Kanji: "上",
    Vocabulary: "ueうえ",
    Type: "Noun, Suffix",
    Meaning: "above; up; over; top; surface",
  },
  {
    Kanji: "生まれる",
    Vocabulary: "umareru うまれる",
    Type: "Verb, Ichidan verb, Intransitive verb",
    Meaning: "to be born",
  },
  {
    Kanji: "海",
    Vocabulary: "umi うみ",
    Type: "Noun",
    Meaning: "sea",
  },
  {
    Kanji: "売る",
    Vocabulary: "uru うる",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to sell",
  },
  {
    Kanji: "煩い",
    Vocabulary: "urusai うるさい",
    Type: "い-adjective",
    Meaning: "noisy, annoying",
  },
  {
    Kanji: "後ろ",
    Vocabulary: "ushiro うしろ",
    Type: "Noun",
    Meaning: "back; behind; rear",
  },
  {
    Kanji: "薄い",
    Vocabulary: "usui うすい",
    Type: "Adjective, い-adjective",
    Meaning: "thin; weak",
  },
  {
    Kanji: "歌",
    Vocabulary: "uta うた",
    Type: "Noun",
    Meaning: "song",
  },
  {
    Kanji: "歌う",
    Vocabulary: "utau うたう",
    Type: "Verb, Godan verb, Intransitive verb, Transitive verb",
    Meaning: "to sing",
  },
  {
    Kanji: "上着",
    Vocabulary: "uwagi うわぎ",
    Type: "Noun",
    Meaning: "coat; tunic; jacket; outer garment",
  },
  {
    Kanji: "ワイシャツ",
    Vocabulary: "wai-shatsu",
    Type: "Noun, Katakana, Wasei",
    Meaning: "shirt",
  },
  {
    Kanji: "若い",
    Vocabulary: "wakai わかい",
    Type: "Adjective, い-adjective",
    Meaning: "young",
  },
  {
    Kanji: "分かる",
    Vocabulary: "wakaru わかる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to understand; to comprehend; to grasp; to see; to get; to follow",
  },
  {
    Kanji: "悪い",
    Vocabulary: "warui わるい",
    Type: "Adjective, い-adjective",
    Meaning: "bad; poor; undesirable",
  },
  {
    Kanji: "忘れる",
    Vocabulary: "wasureru わすれる",
    Type: "Verb, Ichidan verb, Transitive verb",
    Meaning: "to forget",
  },
  {
    Kanji: "渡る",
    Vocabulary: "wataru わたる",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to go across",
  },
  {
    Kanji: "私",
    Vocabulary: "watashi わたし",
    Type: "Pronoun",
    Meaning: "I; myself",
  },
  {
    Kanji: "渡す",
    Vocabulary: "watasu わたす",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to hand over",
  },
  {
    Kanji: "山",
    Vocabulary: "yama やま",
    Type: "Noun",
    Meaning: "mountain; hill",
  },
  {
    Kanji: "八百屋",
    Vocabulary: "yaoya やおや",
    Type: "Noun",
    Meaning: "greengrocer; fruit and vegetable shop; versatile",
  },
  {
    Kanji: "やる",
    Vocabulary: "yaru",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to do",
  },
  {
    Kanji: "野菜",
    Vocabulary: "yasai やさい",
    Type: "Noun",
    Meaning: "vegetable",
  },
  {
    Kanji: "易しい",
    Vocabulary: "yasashii やさしい",
    Type: "Adjective, い-adjective",
    Meaning: "easy, simple",
  },
  {
    Kanji: "安い",
    Vocabulary: "yasui やすい",
    Type: "Adjective, い-adjective",
    Meaning: "cheap; inexpensive",
  },
  {
    Kanji: "休み",
    Vocabulary: "yasumi やすみ",
    Type: "Noun",
    Meaning: "rest; vacation; holiday",
  },
  {
    Kanji: "休む",
    Vocabulary: "yasumu やすむ",
    Type: "Verb, Godan verb, Intransitive verb",
    Meaning: "to be absent; to take a day off; to rest",
  },
  {
    Kanji: "八つ",
    Vocabulary: "yattsu やっつ",
    Type: "Noun, Numeric",
    Meaning: "eight: 8",
  },
  {
    Kanji: "呼ぶ",
    Vocabulary: "yobu よぶ",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to call out, to invite",
  },
  {
    Kanji: "良い",
    Vocabulary: "yoi/ii よい/いい",
    Type: "Adjective, い-adjective",
    Meaning: "good",
  },
  {
    Kanji: "四日",
    Vocabulary: "yokka よっか",
    Type: "Noun",
    Meaning: "fourth day of the month / 4 days",
  },
  {
    Kanji: "横",
    Vocabulary: "yoko よこ",
    Type: "Noun",
    Meaning: "beside,side,width",
  },
  {
    Kanji: "よく",
    Vocabulary: "yoku",
    Type: "Adverb",
    Meaning: "often, well",
  },
  {
    Kanji: "読む",
    Vocabulary: "yomu よむ",
    Type: "Verb, Godan verb, Transitive verb",
    Meaning: "to read;  to guess; to predict; to read (someone's thoughts)",
  },
  {
    Kanji: "夜",
    Vocabulary: "yoru よる",
    Type: "Noun",
    Meaning: "evening; night",
  },
  {
    Kanji: "四つ",
    Vocabulary: "yotsu よつ",
    Type: "Noun, Numeric",
    Meaning: "four; 4",
  },
  {
    Kanji: "洋服",
    Vocabulary: "youfuku ようふく",
    Type: "Noun",
    Meaning: "western clothes",
  },
  {
    Kanji: "八日",
    Vocabulary: "youka ようか",
    Type: "Noun",
    Meaning: "eighth day of the month / 8 days",
  },
  {
    Kanji: "弱い",
    Vocabulary: "yowai よわい",
    Type: "Adjective, い-adjective",
    Meaning: "weak",
  },
  {
    Kanji: "雪",
    Vocabulary: "yuki ゆき",
    Type: "Noun",
    Meaning: "snow",
  },
  {
    Kanji: "ゆっくり",
    Vocabulary: "yukkuri",
    Type: "Adverb",
    Meaning: "slowly",
  },
  {
    Kanji: "昨夜",
    Vocabulary: "yuube ゆうべ",
    Type: "Noun",
    Meaning: "last night",
  },
  {
    Kanji: "郵便局",
    Vocabulary: "yuubinkyoku ゆうびんきょく",
    Type: "Noun",
    Meaning: "post office",
  },
  {
    Kanji: "夕方",
    Vocabulary: "yuugata ゆうがた",
    Type: "Noun",
    Meaning: "evening; dusk",
  },
  {
    Kanji: "夕飯",
    Vocabulary: "yuuhan ゆうはん",
    Type: "Noun",
    Meaning: "evening meal",
  },
  {
    Kanji: "有名",
    Vocabulary: "yuumei ゆうめい",
    Type: "Noun, Adjective, な-adjective",
    Meaning: "famous",
  },
  {
    Kanji: "雑誌",
    Vocabulary: "zasshi ざっし",
    Type: "Noun",
    Meaning: "magazine",
  },
  {
    Kanji: "全部",
    Vocabulary: "zenbu ぜんぶ",
    Type: "Noun, Adverbial Noun",
    Meaning: "all",
  },
  {
    Kanji: "ゼロ",
    Vocabulary: "zero",
    Type: "Noun",
    Meaning: "zero",
  },
  {
    Kanji: "ズボン",
    Vocabulary: "zubon",
    Type: "Noun, Katakana",
    Meaning: "trousers; pants",
  },
];

export default n5Data;
